### PR TITLE
v5_error_correction

### PR DESCRIPTION
**Pull request by kellerza**
From the docs it seems this parameter should be `v5_error_correction` and not `error_correction`?

### CODE REVIEW

**Comment by kellerza** [comment]
Related, what is the best way to ensure a reliable conneciton for constant monitoring?

Is `auto_reconnect=True` enough? Or would you recommend to disconnect & reconnect on a V5FrameError?

**Comment by githubDante** [comment]
Most of the time auto_reconnect is OK. I ended up with handling (NoSocketAvailable, struct.error) in a try/except block, read retry after a second and reconnecting if it fails again. [This is the result](https://imgur.com/a/ed423ZI)

**Comment by kellerza** [comment]
Thanks @githubDante ! 

Are you using [this](https://github.com/githubDante/deye-controller/blob/master/deye_controller/deye_reader.py) to read,- would you recommend re-creating the driver on each read as well?

**Comment by githubDante** [comment]
No. I use a data collect daemon/service built around the library and pysolarman. It is connected to the datalogger 24/7.

I think this is already way beyond the scope of this pull request, so let's move the conversation to an issue if necessary.

**Comment by jmccrohan** [comment]
Well spotted @kellerza. Thanks for your contribution.

**Pull request merged**
